# Generated by Django 5.2.3 on 2025-06-25 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_user(apps, schema_editor):
    """Create a default user if none exists"""
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(id=1).exists():
        User.objects.create_user(
            id=1,
            username='admin',
            email='admin@example.com',
            password='admin123',
            is_staff=True,
            is_superuser=True
        )


def reverse_create_default_user(apps, schema_editor):
    """Remove the default user"""
    User = apps.get_model('auth', 'User')
    User.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_default_user, reverse_create_default_user),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]